package com.example.Networks;

import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

@Service
public class DataCenterService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DataCenterRepository dataCenterRepository;

    @Async
    public void print(String name, String shortdesc, String location, String type, String status, String operatingDate) {

        if(name.equals("") || shortdesc.equals("") || location.equals("") || type.equals("") || status.equals("") || operatingDate.equals("")) {

            int a = 1;
            int b = 0;
            int c = 0;
            c = a / b; //fake exception
        }
        else {
            DataCenter n = new DataCenter();
            n.setName(name);
            n.setShortdesc(shortdesc);
            n.setLocation(location);
            n.setType(type);
            n.setStatus(status);
            n.setOperatingDate(operatingDate);
            dataCenterRepository.save(n);
            System.out.println("Saved");
        }
    }

}