package com.example.Networks;

import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

@Service
public class NetworkService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private NetworkRepository networkRepository;

    @Async
    public void print(String type, String shortdesc, String material, String tech, String owner, String admin) {

            Network n = new Network();
            n.setType(type);
            n.setShortdesc(shortdesc);
            n.setMaterial(material);
            n.setTech(tech);
            n.setOwner(owner);
            n.setAdmin(admin);
            networkRepository.save(n);
            System.out.println("saved");

    }

}