package com.example.Networks;

import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

@Service
public class NetworkService {
    @Autowired
    // Which is auto-generated by Spring, we will use it to handle the data
    private NetworkRepository networkRepository;

    @Async
    public String print(String type, String penetrationRate, String service, String tech, String owner, String admin) {

            Network n = new Network();
            n.setType(type);
            n.setPenetrationRate(penetrationRate);
            n.setService(service);
            n.setTech(tech);
            n.setOwner(owner);
            n.setAdmin(admin);
            networkRepository.save(n);
            return "saved";

    }

}