package com.example.Networks;

import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

@Service
public class SystemsService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SystemsRepository systemsRepository;

    @Async
    public void print(String name, String network, String location, String provider, String status, String operatingDate) {

            Systems n = new Systems();
            n.setName(name);
            n.setNetwork(network);
            n.setLocation(location);
            n.setProvider(provider);
            n.setStatus(status);
            n.setOperatingDate(operatingDate);
            systemsRepository.save(n);
            System.out.println("Saved");

    }

}